### ISSUE TITLE
Multiple ssh keys per user?

### ISSUE THREAD

**Issue by tonydiep** [gmkbenjamin/Andoird-Gitrepo#1]
Is it possible to add multiple ssh keys to the same user?

**Comment by gmkbenjamin** [comment]
Hi @tonydiep 
Thank you for your interest in the project and your suggestion. I've added it in b6949ec23962df6cb299c3fba40286e5fdde63b0 as a quick workaround. You can now add multiple keys and separate them using hyphen "-"

**Comment by tonydiep** [comment]
Hi @gmkbenjamin 

Thanks for your quick response!
